/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LessonsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/emergency': typeof EmergencyRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/api/chat': typeof ApiChatRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/emergency': typeof EmergencyRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/api/chat': typeof ApiChatRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/emergency': typeof EmergencyRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/api/chat': typeof ApiChatRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drills'
    | '/emergency'
    | '/lessons'
    | '/quizzes'
    | '/api/chat'
    | '/lessons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drills'
    | '/emergency'
    | '/lessons'
    | '/quizzes'
    | '/api/chat'
    | '/lessons/$slug'
  id:
    | '__root__'
    | '/'
    | '/drills'
    | '/emergency'
    | '/lessons'
    | '/quizzes'
    | '/api/chat'
    | '/lessons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrillsRoute: typeof DrillsRoute
  EmergencyRoute: typeof EmergencyRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  QuizzesRoute: typeof QuizzesRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof LessonsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LessonsRouteChildren {
  LessonsSlugRoute: typeof LessonsSlugRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsSlugRoute: LessonsSlugRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrillsRoute: DrillsRoute,
  EmergencyRoute: EmergencyRoute,
  LessonsRoute: LessonsRouteWithChildren,
  QuizzesRoute: QuizzesRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
