/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsSlugRouteImport } from './routes/lessons.$slug'

const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsSlugRoute = LessonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drills': typeof DrillsRoute
  '/lessons': typeof LessonsRouteWithChildren
  '/quizzes': typeof QuizzesRoute
  '/lessons/$slug': typeof LessonsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drills' | '/lessons' | '/quizzes' | '/lessons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/drills' | '/lessons' | '/quizzes' | '/lessons/$slug'
  id: '__root__' | '/' | '/drills' | '/lessons' | '/quizzes' | '/lessons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrillsRoute: typeof DrillsRoute
  LessonsRoute: typeof LessonsRouteWithChildren
  QuizzesRoute: typeof QuizzesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$slug': {
      id: '/lessons/$slug'
      path: '/$slug'
      fullPath: '/lessons/$slug'
      preLoaderRoute: typeof LessonsSlugRouteImport
      parentRoute: typeof LessonsRoute
    }
  }
}

interface LessonsRouteChildren {
  LessonsSlugRoute: typeof LessonsSlugRoute
}

const LessonsRouteChildren: LessonsRouteChildren = {
  LessonsSlugRoute: LessonsSlugRoute,
}

const LessonsRouteWithChildren =
  LessonsRoute._addFileChildren(LessonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrillsRoute: DrillsRoute,
  LessonsRoute: LessonsRouteWithChildren,
  QuizzesRoute: QuizzesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
